### ISSUE TITLE
[FR] Support ID links

### ISSUE THREAD

**Issue by NightMachinary** [theiceshelf/firn#100]
`[[id:2318af21-9bab-4ff3-af45-0a760743192e][sth]]` currently goes to `http://localhost:4000/#id:2318af21-9bab-4ff3-af45-0a760743192e` instead of its target. As these links are much better than relative filesystem links (which preclude renames), supporting them would be great. The links can be resolved via `org-id-locations-file`.

**Comment by teesloane** [comment]
Unfortunately, I don't have the time to implement this. Firn is built heavily around relative `file:` links, which was inspired by my usage of org-roam 1.x. I understand org-roam will be moving to id links in subsequent versions but I have no immediate plans to support this. I would be open to reviewing and merging PR's that can support this _and_ retain existing functionality.
