### ISSUE TITLE
italics in blockquote

### ISSUE THREAD

**Issue by holtzermann17** [theiceshelf/firn#103]
Live demo: https://exp2exp.github.io/erg-2021-05-29#framing-%E2%80%98distance%E2%80%99
Screenshot:
![Screenshot from 2021-05-29 22-49-51](https://user-images.githubusercontent.com/179958/120085466-3b90ad80-c0d0-11eb-8d11-3857d9f24698.png)

Source code:

```
*** Framing ‘distance’
#+begin_quote
/Initially treated as an esoteric distinction of interest only to
specialists in the field of ontology, since the advent of computer
games, and more especially the Internet, this distinction has become
very important because it allows that what is seen or experienced on
screen is still REAL, even if it isn't ACTUAL./

—  “actual and virtual”, in /A Dictionary of Critical Theory/
#+end_quote
```

**Comment by teesloane** [comment]
Regrettably, the parser does not parse within quote blocks - I'm assuming because it expects quotes to be verbatim / [sic]?

**Comment by teesloane** [comment]
This is fixed by the re-write :).
