### ISSUE TITLE
Is it Possible to Use the HTML_HEAD Directive?

### ISSUE THREAD

**Issue by tompurl** [theiceshelf/firn#116]
I would like to move some of my firn pages to a different host. I would therefore like to use a header redirect that would look something like this:

``` org-mode
#+HTML_HEAD <meta http-equiv="Refresh" content="0; url='https://www.tomswiki.com'" />
```

However, it doesn't seem that this setting is exported to the page. How would I go about supporting something like this?

**Comment by teesloane** [comment]
You should be able to access custom front matter  under the `other` key in the frontmatter object:

For example, I set a hero on a per-page basis using a `#+HERO_IMG` front matter key/value. 
```html
        {% if frontmatter.other.hero_img %}
        <div class="hero-img" style="background-image: url('{{frontmatter.other.hero_img}}')"></div>
        {% endif %}

```
Let me know if that works for you.

**Comment by tompurl** [comment]
This worked *perfectly* @teesloane :-) Here's what I added to the `<head>` section of `head.html`:

```
    {% if frontmatter.other.html_head %}
    {{frontmatter.other.html_head}}
    {% endif %}
```

Thank you for the quick help!
