### ISSUE TITLE
The website (https://theiceshelf.com/) is redirecting to a shady URL

### ISSUE THREAD

**Issue by tad-lispy** [theiceshelf/firn#117]
Hey @teesloane ! Just popping in to let you know that there is something off with your website `theiceshelf.com`. All URLs and subdomains redirect to `http://vibiu-dau.com/zclkredirect?visitid=eb9c60b2-5dd7-11ee-8abd-0a33fcfa7a4b&type=js&browserWidth=1920&browserHeight=995&iframeDetected=false&webdriverDetected=false` which is blocked by my ad-blocker.

![image](https://github.com/teesloane/firn/assets/1684495/71182a92-257a-4191-a924-09a6dd7d8390)

Looks like someone hijacked your domain :-(

**Comment by teesloane** [comment]
Hi!

Thanks for letting me know. I have actually let the domain lapse, so
someone else has (surprisingly) snagged it. I will remove all references
from the repos when I get back from a vacation.

Cheers,

WT

**Comment by tad-lispy** [comment]
You are welcome and please enjoy your vacation. BTW the other site of yours (https://weakty.com/) is really lovely. Is it build using Firn?

**Comment by teesloane** [comment]
> You are welcome and please enjoy your vacation. BTW the other site of yours (https://weakty.com/) is really lovely. Is it build using Firn?

It was, for a long time, yeah! But I've recently migrated to a database backed site.
