### ISSUE TITLE
Automated documentation website as preview of firn capacity ?

### ISSUE THREAD

**Issue by reyman** [theiceshelf/firn#19]
Hi @teesloane !

This is an idea copy/pasted from ox hugo website, i think that could be a good way to demonstrate capacity of Firn : 
- a documentation website generated with Firn like  https://ox-hugo.scripter.co/ 
- a debug/test website for issue like https://ox-hugo.scripter.co/test/

I think that could be interesting because a noob user in org or firn could see the template/structure of org file needed to generate this site. 

Best regards,
SR

**Comment by teesloane** [comment]
Hey @reyman!

This is a great idea. I have started a docs folder in the repo to document features/usage, but it is all setup to eventually be converted into a stand-alone Firn site. I will perhaps aim for this for the v0.0.6 release.

**Comment by teesloane** [comment]
Closed in #22 
The [new site](https://firn.theiceshelf.com/) provides documentation - although in another PR I will add a "debug/elements" page that lists elements of an org-site.
