### ISSUE TITLE
Out of the box html layout less minimalist/raw ?

### ISSUE THREAD

**Issue by reyman** [theiceshelf/firn#20]
Hi @teesloane !

The first time i build my org folder with firn, and i open the result, i'm very surprised by the really minimalist/raw html output. 

I think there is some ambiguity with the link to your personnal firn website "theiceshelf" (https://wiki.theiceshelf.com/firn), because future user could be surprised by the fact that this is not the real output of Firn out-of-the-box.

This is probably on roadmap, but a default layout less raw that actual will probably attract more user :) 

Thanks for your work :+1:

**Comment by edhilgendorf** [comment]
Same -- clarification just sample output of what to expect would be great so we can compare and see if it actually built correctly!

**Comment by teesloane** [comment]
Bonjour @reyman ! Oui, c'est un peu plaindre, n'est pas? 

Good point, both. I have been working on my personal wiki for a while, but it was all built with Firn :). Generally, I air toward trying to include as few dependencies in a project (fonts, css, js, etc) as possible and leaving that up to the user. But, I will try and make both the future docs site and the "out of the box" experience a bit more pleasant. Cheers!

**Comment by reyman** [comment]
I'm searching some existing org export html template and i update this post with link : 
- https://github.com/fniessen/org-html-themes
- https://thomasf.github.io/solarized-css/
