### ISSUE TITLE
Community  ? 

### ISSUE THREAD

**Issue by reyman** [theiceshelf/firn#23]
Hi @teesloane ! 

Super boulot sur la future release, le nouveau style css est très bien :)

Switch to english. Don't know if you plan to create a community channel (discord like doom-emacs, discourse, matrix or anything else on the vast chat app universe ...) but that could be a good idea to discuss and exchange idea/things about firn !!

For example, don't know if you see the org parser of organice, also usable in clojure : https://github.com/200ok-ch/org-parser 

Best regards,

**Comment by teesloane** [comment]
Merci @reyman, et merci pour l'idée!

I use Discord occasionally, so I setup [a server](https://discord.gg/TbgKxYb); please join and say hello! Would love to chat about Firn, projects, or whatever. 

As for Organice's parser - I did a brief evaluation of it, but by that time I was already invested with the syntax tree created by Organize -- but who knows -- maybe I'll be able to go full Clojure someday soon! See you on the chat!
