### ISSUE TITLE
Question: how customizable are sites built with firn intended to be?

### ISSUE THREAD

**Issue by yosevu** [theiceshelf/firn#24]
Hey, just discovered this project!

Love that this is built with Clojure! I'm using [org-roam](https://github.com/org-roam/org-roam/) for my notes and wondering: would it be possible to build a theme that integrates links between notes like gatsby-theme-andy does?

- Example: https://notes.aravindballa.com/
- Source: https://github.com/aravindballa/gatsby-theme-andy

**Comment by yosevu** [comment]
Ah, reading the docs and seeing Org-roam mentioned 😊

**Comment by teesloane** [comment]
Hi @yosevu  - this is a good question.  The short answer is - no, this is not currently possible. Long answer - it might be in a future release. For now, Firn is meant to ship a static site without any JS. However, I intend to investigate attaching either the parsed org content or a munged version of it that can be made accessible to a (probably) ClojureScript layer in the future. This would be useful for building charts, graphic connections between notes, and possible higher-level interactions like you mentioned. Ideally, I'd like to leave most of that up the user. Either way, I'll be thinking about it for a few weeks as I finish other core features.
