### ISSUE TITLE
Support attachments (file links) other than images

### ISSUE THREAD

**Issue by mroman42** [theiceshelf/firn#49]
I have a PDF on the =data= folder that I want to link from a page (not to embed as an image).  In the org-mode document, I add a link `[[file:data/my.pdf]]`, but it gets later exported to a link to `#file:mypdf` in the final HTML.  The PDF, however, gets correctly copied to the `_site` folder.

The same method, however, works for embedding images. 

Is it possible to use file links to attach documents other than images?

**Comment by teesloane** [comment]
Yep, this should be possible—thank you for pointing that out. I will slate it for 0.0.11!

**Comment by teesloane** [comment]
This is in master and will ship with 0.0.11.
