### ISSUE TITLE
Rendering math properly and mathjax support through custom css

### ISSUE THREAD

**Issue by sleepyeye** [theiceshelf/firn#56]
Hi!

I'm tryting to export my personal org-mode wiki to static webpages through firn.
However I found that latex fragments are not rendered properly with the default firn setting.
Am I missing something or is firn not ready to handle equations properly?

Ultimately, I am planning to apply custom css such as [latex-css](https://github.com/vincentdoerig/latex-css) or [org-css](https://github.com/gongzhitaao/orgcss) which supports mathjax out-of-box.
Can I change default css to the others so that my equations can be rendered with mathjax?
I presume this functionality is going to be supported after reading some previous issues but I'm not sure enough.

**Comment by teesloane** [comment]
Hi there!

Unfortunately, I know very little about this domain. I am not even sure if the parser Firn uses can parse latex (or how org does it). As of now, this will not be on the roadmap until other features get planned and executed. I would be happy to review and consider a pull request that could include this functionality.

**Comment by sleepyeye** [comment]
As far as I know, you don't need to parse latex fragments rather you just wrap them with proper HTML elements.
For example, the example page of [orgcss](https://gongzhitaao.org/orgcss/)(see 5.5.4) and its corresponding HTML source is as follows
```html
...
 <span class="section-number-4">5.5.4</span> Math</h4>
<div class="outline-text-4" id="text-5-5-4">\begin{align} \mathcal{F}(a) &= \frac{1}{2\pi i}\oint_\gamma \frac{f(z)}{z - a}\,dz\\ \int_D (\nabla\cdot \mathcal{F})\,dV &=\int_{\partial D}\mathcal{F}\cdot n\, dS \end{align}</div>
...
```
This seems right but I'm not sure since I don't have enough knowledge related to HTML/CSS.

**Comment by holtzermann17** [comment]
Firstly, since "parsing" is really an Orgize issue, I noted it as such :point_up: :point_right:  https://github.com/PoiScript/orgize/issues/42

Secondly, I think "CSS" in the title here is somewhat misleading, since MathJaX is based on JS (not CSS).

And finally — to that end — here's a version of `head.clj` that brings in MathJaX support and configures it so that $x$ renders as *x*.

```clojure
(defn head
  [build-url]
  [:doctype :html5]
   [:head
    [:meta {:charset "UTF-8"}]
    [:meta {:name "viewport" :content "width=device-width, initial-scale=1.0"}]
    [:script {:type "text/x-mathjax-config"}
     (str "MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ['\\\\(','\\\\)'] ],
      processEscapes: true
    }
  });")]
    [:script {:src "https://polyfill.io/v3/polyfill.min.js?features=es6"}]
    [:script {:type "text/javascript" :async "async" :src "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"}]
    [:link {:rel "stylesheet" :href (build-url "/static/css/firn_base.css")}]])
```

Minimal deployed demo here:
https://exp2exp.github.io/20200810131435-hyperreal_enterprises#we-are-looking-at-this-problem-as-an-informal-open-source-r&d-collective

**Comment by holtzermann17** [comment]
Can we close this now?
