### ISSUE TITLE
"File does not have 'front-matter' and will not be processed"

### ISSUE THREAD

**Issue by slondr** [theiceshelf/firn#64]
I followed the getting started guide in the documentation but it doesn't work for me. Here's my org file (`index.org`):

```
#+title: Hello world
* Test heading
```
I get the following error when I run `firn serve`:
`Warning: File << index >> does not have 'front-matter' and will not be processed.`

Sure enough, the exported HTML has no content beyond empty div tags. 
I followed the documentation as closely as I can, so either the docs are wrong or firn is doing something I don't understand

**Comment by teesloane** [comment]
Try upcasing `#+title:` -> `#+TITLE:`

**Comment by slondr** [comment]
> Try upcasing `#+title:` -> `#+TITLE:`

Wait, is this required? The org spec allows either case, and in fact [officially prefers lowercase elements](https://code.orgmode.org/bzg/org-mode/commit/13424336a6f30c50952d291e7a82906c1210daf0) as of a couple years ago

**Comment by teesloane** [comment]
Right now, yep. Will fix this in the next release :).
