### ISSUE TITLE
Doesn't like directories with ".org" in

### ISSUE THREAD

**Issue by elken** [theiceshelf/firn#66]
Problem seems to lie [here](https://github.com/theiceshelf/firn/blob/master/clojure/src/firn/util.clj#L66) not checking if what it finds is actually a file or not.

![image](https://user-images.githubusercontent.com/2872862/102691939-0e2e0280-4208-11eb-9d9e-7a2e21295470.png)

**Comment by teesloane** [comment]
That should be an easy fix. I'll patch it into master, but the next release will likely not be up for a month or two. Thanks for reporting.
