### ISSUE TITLE
export special blocks

### ISSUE THREAD

**Issue by holtzermann17** [theiceshelf/firn#68]
In regular Org mode, it’s possible to [define your own blocks](https://superuser.com/questions/726201/how-can-i-apply-easy-formatting-to-org-mode-blocks) which are then exported to a `div` with the given block name, e.g.,

```
#+begin_monoblock
This is some text.
#+end_monoblock
```

turns into

```
<div class="monoblock" id="org6f3fd59">
<p>
This is some text.
</p>

</div>
```

The relevant code is in `org-html-special-block` in ox-html.el.  With Firn, it seems these blocks aren’t currently exported, but they're confirmed to be recognized in the [Orgize JSON export](https://orgize.herokuapp.com). Could they be enabled here?

**Comment by holtzermann17** [comment]
**Note, as a further special request:**

For my use case, I'd actually want to export the blocks to `span` rather than `div`, although the standard Org Mode exporter, ox-html.el, would always export to `div`.  I wonder what how this extra level of customization might be arranged?

**Comment by teesloane** [comment]
Gotcha, thanks for the update. I think handling for special-blocks should be simple. It will be like the example ox-hugo, but will render the blocktype as a class rather than an id. (although, it seems like there is an opportunity for a fair bit of "expansability" with allowing people to determine how different blocks be parsed at runtime; I will have to think about it for a future release). 

Do you mind sharing why it should be a `span`? Could you not use a div and style the class of it to resemble a span?

**Comment by holtzermann17** [comment]
Ah, you're right, it can all be changed with CSS!

> As you already know [but I didn't! -JC] the difference between a `<div>` and a `<span>` is just that one defaults to `display:block;` and the other to `display:inline;`. To make one act as the other, just set the display style to the other type.  ([source](https://stackoverflow.com/a/3821719/821010))

**Comment by holtzermann17** [comment]
This brief update is beyond the scope of Firn but in my attempt to mock up a preliminary solution by hand, I couldn't get the special block to display properly with `display:inline;`

https://gist.github.com/holtzermann17/c907d070cff649e7c9c5665aa7cf325e

**Comment by holtzermann17** [comment]
OK, I figured out why it isn't working: 

>  'display', 'position', and 'float' — interact as follows: ... if 'float' has a value other than 'none', the box is floated and 'display' is set according to the table below: 
> **Specified value** | **Computed value**
> -- | --
> | inline, table-row-group, table-column, table-column-group, table-header-group, table-footer-group, table-row, table-cell, table-caption, inline-block | block |
>
> — https://www.w3.org/TR/CSS2/visuren.html#dis-pos-flo

**Comment by holtzermann17** [comment]
Just to mention:
```
#+BEGIN_LATEX
x!+y!
#+END_LATEX
```
would be a special case, and if handled nicely would be a stop-gap solution to the "LaTeX environment" part of #56... (and a viable alternative for most sensible people in day-to-day use).
