### ISSUE TITLE
Relative links and subdirectories

### ISSUE THREAD

**Issue by holtzermann17** [theiceshelf/firn#77]
In brief, links to files inside the same directory Org Roam are stored without the directory information — because that isn't needed to find the files.  But this doesn't work when exporting with Firn

# Example

> *** [[file:emacs-research-notes.org::*Everyone shared a brief intro and ideas so we got to know each other][Everyone shared a brief intro and ideas so we got to know each other]] :ep1:

That exports to a link:

`http://localhost:4000/emacs-research-notes#everyone-shared-a-brief-intro-and-ideas-so-we-got-to-know-each-other`

But in fact the file is in the `./erg/` subdirectory of my `org-roam-directory`, so that link doesn't work!

I can hack it so that the export "works" and produces a valid link in the downstream HTML:

# Example

> *** [[file:./erg/emacs-research-notes.org::*Everyone shared a brief intro and ideas so we got to know each other][Everyone shared a brief intro and ideas so we got to know each other]] :ep1:

But now such links don't make sense to Org Roam anymore! (They turn red).

Furthermore, in Org Roam, links to files *in other directories* are stored with the full path.

# Example

> *** [[file:~/exp2exp.github.io/src/week_11_january_2021.org::*News][News]]

But this doesn't make sense to Firn: it comes out as a link to: `http://localhost:4000/~/exp2exp.github.io/src/week_11_january_2021#news`

**Comment by teesloane** [comment]
I'm not sure if this is new org-roam functionality - any chance you can walk me through how you are creating links step by step. For example - this is how I use org-roam


https://user-images.githubusercontent.com/12987958/105105291-d376ee80-5a81-11eb-884a-b99057c40f02.mp4

I will check in with org-roam's docs - if I am understanding the problem correctly,  it sounds like perhaps roam links might not have to store relative / dir paths now.

**Comment by jarhodes314** [comment]
A quick look at this suggests that this may be the same bug I encountered, which is caused by the fact the link is in a headline. If it is, it would have been fixed in https://github.com/theiceshelf/firn/pull/79. I think I understood the problem correctly, and testing my build with the change locally seemed to produce the result you were looking for. Since that PR is merged now, @holtzermann17 you should be able to check whether it now works as you intended if you build from master?

**Comment by holtzermann17** [comment]
@jarhodes314 

Yes, this seems to work perfectly now.  Tested with this file, inside `./testing/` subdirectory.  All links work.

```org
#+TITLE: Broadcast

This is a [[file:test.org][Test]] of the [[file:../emergency.org][Emergency]] broadcast system.

* [[file:test.org][Test]]
* [[file:../emergency.org][Emergency]]
```
