### ISSUE TITLE
bold text in headline

### ISSUE THREAD

**Issue by holtzermann17** [theiceshelf/firn#78]
This example:

`**** Getting the shared *Zettlekasten* / OR working!`

Exports to:

> `<div class="firn-headline-section firn-headline-section-4"><h4 class="firn-headline firn-headline-4" id="getting-the-shared--or-working!"><span class="firn-headline-text"><span>Getting the shared </span><strong><span>Zettlekasten</span></strong><span> / OR working!</span></span></h4><section><ul><li><p><span>(Zettlekasten isn’t yet a solved problem.)</span></p></li></ul></section></div>`

With the result that the space between "shared" and "**Zettlekasten**" goes away.

**Comment by jarhodes314** [comment]
This seems to be an issue with the CSS. On `span.firn-headline-text`, the default stylesheet has `display: flex`, which will effectively suppress the spaces by placing the children directly next to each other. Removing the `display: flex` style, e.g. by removing the following lines (352-357 on master) from `firn_base.css` fixes this behaviour.

```css
.firn-headline-text {
    display: flex;
    flex: 1;
    align-items: center;
}
```

A quick peek at the git blame for that file suggests that https://github.com/theiceshelf/firn/commit/aa5f75742241a5af6e6a71463bf06e43eb2e210e (from PR #26) added this styling, presumably to help with vertical alignment of tags in headlines.

**Comment by holtzermann17** [comment]
Thanks for the info. Removing that line from the CSS fixes the display on my site:
https://exp2exp.github.io/erg-02-01-2021#Getting-the-shared-Zettlekasten-/-OR-working!

**That said**, I don't notice any detectable difference to vertical display of tags based on turning `display: flex;` on and off.

![Screenshot from 2021-02-07 17-46-23](https://user-images.githubusercontent.com/179958/107154737-8c876500-696c-11eb-999c-07c4f8d9c270.png)
![Screenshot from 2021-02-07 17-46-15](https://user-images.githubusercontent.com/179958/107154738-8d1ffb80-696c-11eb-981a-485dc08a46a4.png)

I do think it would look nicer if the tags were aligned with the top of the headline, but I don't know how to make that happen.

**Comment by teesloane** [comment]
Great !  I will close this in that case. 

Regarding alignment:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/12987958/107158357-73c08480-6957-11eb-9795-9f2d65a8d2dc.png">

Changing `align-items` might help. However, you may still have to putter with the margin/padding on the tag item to align as you like.
