### ISSUE TITLE
Question: unnecessary dependencies for the Rust lib?

### ISSUE THREAD

**Issue by jarhodes314** [theiceshelf/firn#80]
I had a quick flick through `rust/Cargo.toml` and found, to my surprise, that it depends on the crate `heim`. Looking through the source code, it seems like this isn't actually used, and since it depends on `uom` (which leans very heavily on generics), this adds a considerable amount of time to compiling the Rust code. It also seems to depend on `futures` without using that.

Is there a reason for these dependencies to be present? https://github.com/theiceshelf/firn/commit/d297b584139c6caa8bf7f07f62bf846b852de212 seems to suggest that both `heim` and `futures` were used in the example code in https://github.com/borkdude/clojure-rust-graalvm/blob/master/rust/src/lib.rs, but have never been necessary for firn.

Being a Rustacean myself, I'm more than happy to fix this along with running the code through the formatter and linter, but just want to check that there isn't something I'm missing before I go ahead and make any changes.

**Comment by teesloane** [comment]
It sounds like I left the dependencies in by nature of copying borkdude's work during my MVP development. If you can delete them and free up some compilation time that would be most welcome.

**Comment by teesloane** [comment]
Closed by https://github.com/theiceshelf/firn/commit/bf3aa69f1982777e6d40e3d6b702301ffa989ad8
