### ISSUE TITLE
#+title: breaks things, but should be allowed

### ISSUE THREAD

**Issue by holtzermann17** [theiceshelf/firn#91]
Firn expects `#+TITLE:` but `#+title:` is acceptable to Org Mode and is the new default for page creation in Org Roam. 

(Should be an easy ticket for anyone who wants something small to get started with, just logging it to be thorough.)

**Comment by teesloane** [comment]
@holtzermann17 what version are you on? I've got this working in `0.13`, and I believe this was fixed by 7053b5b.

**Comment by holtzermann17** [comment]
Confirmed to work on recent build.
