### ISSUE TITLE
feature request: show first image on page as thumbnail/preview

### ISSUE THREAD

**Issue by holtzermann17** [theiceshelf/firn#95]
It seems this is a matter of writing a 'partial' but I'm not immediately sure just what it would look like.
Here, someone is writing about how they do it in Hugo:
https://discourse.gohugo.io/t/display-first-image-in-post-in-link-preview/10541/2

Sample page with an image on it:

https://exp2exp.github.io/writers_workshop

Reposted in Discord, no preview shows up (that's expected at the moment, but the feature request would be to generate a preview):

![Screenshot from 2021-04-17 15-34-54](https://user-images.githubusercontent.com/179958/115116638-84fac280-9f92-11eb-9eef-909dbe35931f.png)

**Comment by teesloane** [comment]
Yep, this could be done with a partial. I think this is a bit adjacent to Firn so I wouldn't add it to the docs, but for the most part, I think the process would look like this: 
- add required [metadata]https://ogp.me/#metadata) to your head partial (if you have one)
- pass file metadata (from keywords, or just from `title` etc, into your head partial as a map (`ogp-data`). 
- If you want images, you could probably store an image as a `#+frontmatter` key too!

Let me know if this works.
