### ISSUE TITLE
feature request: can we add more TODO types?

### ISSUE THREAD

**Issue by holtzermann17** [theiceshelf/firn#98]
I like to use `BACK` for backlogged items that haven't yet become active as `TODO` items (and a few other strings).  Currently Firn only does `TODO` and `DONE`. It would be nice if the selection of todo types was configurable in the `.edn`.

**Comment by teesloane** [comment]
I've been meaning to look into this but haven't had the time. This should be possible by passing values from config.edn over the bridge to Rust:

Where this [line](https://github.com/theiceshelf/firn/blob/085d908531231b76079dd394b64caf78e686ccc0/rust/src/lib.rs#L36) will be replaced by the custom parser with the ability to define custom keywords:

```
use orgize::{Org, ParseConfig};

Org::parse_custom(
    "* TASK Title 1",
    &ParseConfig {
        // custom todo keywords
        todo_keywords: (vec!["TASK".to_string()], vec![]),
        ..Default::default()
    },
);
```
